import { canonicalJson, requestDigest } from "./canonical.mjs";

// Cases chosen where a Rust implementation can plausibly disagree with JavaScript, not where it
// obviously agrees. The UTF-16 ordering ones are the reason this file exists.
//
// Every non-ASCII and control character is written as an escape rather than a literal, so this
// source stays plain ASCII and nothing between here and Node can quietly alter what is tested.
// Generated by write_fixtures_mjs.py; see README.md.
const CASES = [
  ["empty object", "greencal_list_meetings", {}],
  ["flat, already sorted", "greencal_get_meeting", { a: 1, b: "two", c: true }],
  ["flat, needs sorting", "greencal_get_meeting", { c: true, a: 1, b: "two" }],
  ["null and false", "greencal_get_booking_rules", { z: null, y: false }],
  ["nested objects and arrays", "greencal_list_notetakers", {
    outer: { inner: [1, { k: "v" }, []], flag: false },
    list: ["b", "a"],
  }],
  ["array order is preserved", "greencal_list_meetings", { items: [3, 1, 2] }],
  ["negative and zero", "greencal_update_meeting", { a: -1, b: 0, c: -0 }],
  ["max safe integer", "greencal_update_meeting", { n: 9007199254740991 }],
  ["min safe integer", "greencal_update_meeting", { n: -9007199254740991 }],
  ["quotes and backslashes", "greencal_get_booking_link", { s: 'he said "hi" \\ bye' }],
  ["control characters", "greencal_get_booking_link", {
    s: "a\bb\tc\nd\fe\rf\u0000g\u001fh",
  }],
  ["non-ascii stays literal", "greencal_get_booking_link", {
    s: "caf\u00e9 \u2615 \u65e5\u672c\u8a9e",
  }],
  ["emoji key and value", "greencal_get_booking_link", { "\u{1F511}": "\u{1F512}" }],
  ["utf16 vs codepoint key order", "greencal_get_booking_link", {
    "\u{10000}": "supplementary",
    "\uffff": "bmp-high",
  }],
  ["surrogate ordering, three keys", "greencal_get_booking_link", {
    "\ue000": "private-use",
    "\u{1F600}": "emoji",
    "\ufffd": "replacement",
  }],
  ["ascii vs non-ascii key order", "greencal_get_booking_link", {
    "z": 1, "A": 2, "_": 3, "0": 4, "\u00e9": 5,
  }],
  ["empty string key", "greencal_get_booking_link", { "": "empty", "a": "x" }],
  ["mutation body with requestKey", "greencal_update_booking_rules", {
    requestKey: "test-request-key-0000000000000000",
    expectedVersion: 7,
    window: { weekday: 3, start: "09:00", end: "17:00", timezone: "Europe/London", active: true },
  }],
  ["deep nesting near the cap", "greencal_get_meeting", (() => {
    let node = { leaf: 1 };
    for (let i = 0; i < 25; i++) node = { [`level${i}`]: node };
    return node;
  })()],
];

const out = [];
for (const [name, operation, body] of CASES) {
  out.push({
    name,
    operation,
    body,
    canonical: canonicalJson(body),
    digest: await requestDigest(operation, body),
  });
}
console.log(JSON.stringify(out, null, 2));
