export const CONTAINER_PORT = 8080;

export const GREEN_GATEWAY_ENV_KEYS = [
  "ADMIN_PREFIX",
  "ADMIN_LOGIN_PROVIDER",
  "GATEWAY_PUBLIC_URL",
  "AUDIT_LOG_FILE",
  "AUDIT_SQLITE_PATH",
  "AUDIT_SQLITE_RETENTION_DAYS",
  "DISCOVERY_SQLITE_PATH",
  "PRINCIPAL_SQLITE_PATH",
  "PAYLOAD_CAPTURE_ENABLED",
  "PAYLOAD_CAPTURE_SAMPLE_RATE",
  "SCHEMA_MISMATCH_SIGNAL_THRESHOLD",
  "ERROR_RATE_SPIKE_SIGNAL_THRESHOLD",
  "PRINCIPAL_NEW_TO_ENDPOINT_SIGNAL_THRESHOLD",
  "VOLUME_OUTLIER_SIGNAL_THRESHOLD",
  "RULE_SUGGESTION_BASELINE_WINDOW_HOURS",
  "OPENAPI_SPEC_PATH",
  "POLICY_FILE",
  "TOOLS_FILE",
  "MCP_UPSTREAM_SERVERS",
  "POLICY_HISTORY_SQLITE_PATH",
  "RBAC_EXEMPT_PATHS",
  "CORS_ALLOW_ORIGINS",
  "MAX_BODY_SIZE",
  "RATE_LIMIT_READ_RPS",
  "RATE_LIMIT_READ_BURST",
  "RATE_LIMIT_WRITE_RPS",
  "RATE_LIMIT_WRITE_BURST",
  "TRUST_PROXY_HEADERS",
  "TRUSTED_PROXY_CIDRS",
  "VALIDATION_ALLOWED_CONTENT_TYPES",
  "AUTH_ENABLED",
  "AUTH_MODE",
  "AUTH_COOKIE_NAME",
  "AUTH_EXEMPT_PATHS",
  "AUTH_PROVIDERS",
  "JWT_JWKS_URL",
  "JWT_ISSUER",
  "JWT_AUDIENCE",
  "JWT_JWKS_TIMEOUT_MS",
  "JWT_REQUIRE_JTI",
  "ROLES_CLAIM",
  "SERVICE_TOKEN_SQLITE_PATH",
  "SERVICE_TOKEN_CACHE_TTL_MS",
  "TOOL_RUNTIME_QUEUE_DEPTH",
  "TOOL_RUNTIME_GLOBAL_CONCURRENCY",
  "TOOL_RUNTIME_QUEUE_TIMEOUT_MS",
  "TOOL_RUNTIME_DEFAULT_TIMEOUT_MS",
  "CSRF_ENABLED",
  "CSRF_COOKIE_NAME",
  "CSRF_HEADER_NAME",
  "CSRF_COOKIE_DOMAIN",
  "CSRF_EXEMPT_PATHS",
  "UPSTREAM_URL",
  "UPSTREAM_ROUTES",
  "UPSTREAM_TIMEOUT_MS",
  "UPSTREAM_RESPONSE_IDLE_TIMEOUT_MS",
  "UPSTREAM_CONNECT_TIMEOUT_MS",
  "EGRESS_ALLOWED_HOSTS",
  "EGRESS_TIMEOUT_MS",
  "EGRESS_RESPONSE_IDLE_TIMEOUT_MS",
  "EGRESS_CONNECT_TIMEOUT_MS",
  "EGRESS_MAX_RESPONSE_BYTES",
  "EGRESS_MAX_REQUEST_BODY_BYTES",
  "EGRESS_DENY_PRIVATE_IPS",
] as const;

export type GreenGatewayEnvKey = (typeof GREEN_GATEWAY_ENV_KEYS)[number];
export type GreenGatewayWorkerEnv = Partial<Record<GreenGatewayEnvKey, string>>;

export function buildGreenGatewayContainerEnv(
  env: object,
): Record<string, string> {
  const containerEnv: Record<string, string> = {};
  const bindings = env as Record<string, unknown>;

  for (const key of GREEN_GATEWAY_ENV_KEYS) {
    const value = bindings[key];
    if (typeof value === "string" && value.trim().length > 0) {
      containerEnv[key] = value;
    }
  }

  containerEnv.LISTEN_ADDR = `0.0.0.0:${CONTAINER_PORT}`;
  return containerEnv;
}
